# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/walkwithfastai',
                'doc_host': 'https://pmaxit.github.io',
                'git_url': 'https://github.com/pmaxit/walkwithfastai',
                'lib_path': 'walkwithfastai'},
  'syms': {'walkwithfastai.core': {'walkwithfastai.core.foo': ('core.html#foo', 'walkwithfastai/core.py')}}}
