# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/walkwithfastai',
                'doc_host': 'https://pmaxit.github.io',
                'git_url': 'https://github.com/pmaxit/walkwithfastai',
                'lib_path': 'walkwithfastai'},
  'syms': { 'walkwithfastai.core': { 'walkwithfastai.core.Number': ('core.html#number', 'walkwithfastai/core.py'),
                                     'walkwithfastai.core.Number.__add__': ('core.html#number.__add__', 'walkwithfastai/core.py'),
                                     'walkwithfastai.core.Number.__init__': ('core.html#number.__init__', 'walkwithfastai/core.py'),
                                     'walkwithfastai.core.Number.__repr__': ('core.html#number.__repr__', 'walkwithfastai/core.py'),
                                     'walkwithfastai.core.foo': ('core.html#foo', 'walkwithfastai/core.py'),
                                     'walkwithfastai.core.say_hello': ('core.html#say_hello', 'walkwithfastai/core.py')}}}
